# Generated by Django 4.2.1 on 2023-05-10 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloogapp', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
